/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "zgobandServerThrift_constants.h"

namespace zgobandRPC {

const zgobandServerThriftConstants g_zgobandServerThrift_constants;

zgobandServerThriftConstants::zgobandServerThriftConstants() {
}

} // namespace

