/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef zgobandServerThrift_CONSTANTS_H
#define zgobandServerThrift_CONSTANTS_H

#include "zgobandServerThrift_types.h"

namespace zgobandRPC {

class zgobandServerThriftConstants {
 public:
  zgobandServerThriftConstants();

};

extern const zgobandServerThriftConstants g_zgobandServerThrift_constants;

} // namespace

#endif
